### PR TITLE
Fix  #526

### LINKED ISSUE #526: Compatibility issues with the Bakery WordPress theme
**Describe the bug**
A compatibility issue with the [Bakery WordPress theme](https://themeforest.net/item/bakery-wordpress-bakery-cakery-food-theme/11112118?s_rank=1) prevents the delivery time slots picker from working and being selectable on the checkout page.

image

**To Reproduce**
To reproduce this issue, you need to install the Bakery WordPress theme.

**Additional context**
[https://tychesoftwares.freshdesk.com/a/tickets/62300](https://tychesoftwares.freshdesk.com/a/tickets/62300)

### PR DESCRIPTION
**Pull request by nidhi-tatosaniya**
Fixed Compatibility issues with the Bakery WordPress theme
Fix https://github.com/TycheSoftwares/order-delivery-date-for-woocommerce/issues/526

### CODE REVIEW

File: order_delivery_date.php [hunk 1]
```diff
@@ -699,6 +700,19 @@ public static function orddd_lite_admin_rate_us( $footer_text ) {
...
+		/**
+		 * Bakery_enqueue_scripts.
+		 *
+		 * @since 3.11.0
+		 * @param array $scripts The all scripts name.
+		 * @return array
+		 */
+		public function bakery_enqueue_scripts( $scripts ) {
+			if ( 'bootstrap-datepicker' === $scripts[5] ) {
+				unset( $scripts[5] );
```
Comment (rashmimalpande) [inline order_delivery_date.php:712]: can we add this check in foreach loop so that there will be no issues if $scripts values are changed?

**Review by rashmimalpande — CHANGES_REQUESTED** [review]

**Review by rashmimalpande — APPROVED** [review]
