### PR TITLE
Fix #486

### LINKED ISSUE #486: When we place an order with first available delivery date, it's not getting appeared on Order page or in email
**Describe the bug**
I have a problem with free "Order Delivery Date" plugin in Wordpress/woocommerce. When i place an order and dont select the "Order Delivery Date" (system shows the first available date by default) and only choose "Delivery time slot" the woocommerce email that the client gets dosent show "Delivery Date" only shows "Delivery time". 
Screenshots:
https://ibb.co/DLYP9VN
https://ibb.co/KjRfkgN

**To Reproduce**
I can replicate this on client's site only. Even with the same setup of the plugin, the issue is not being reproduced on my staging site. 

**Expected behavior**

**Screenshots or Video**
image

image

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/50025

### PR DESCRIPTION
**Pull request by nidhitatosaniya**
Added value for 'e_deliverydate' hidden field in Fix #486

### CODE REVIEW

File: js/orddd-lite-initialize-datepicker.js [hunk 1]
```diff
@@ -394,6 +394,7 @@ if ( typeof( e_deliverydate_session ) != 'undefined' && e_deliverydate_session !
 		var default_date     = new Date( default_date_arr[ 1 ] + '/' + default_date_arr[ 0 ] + '/' + default_date_arr[ 2 ] );
 		jQuery( '#e_deliverydate' ).datepicker( "setDate", default_date );
 		jQuery( "#h_deliverydate" ).val( h_deliverydate_session );
+		jQuery( 'input[name="e_deliverydate"]' ).val( h_deliverydate_session );
```
Comment (rashmimalpande) [inline js/orddd-lite-initialize-datepicker.js:397]: @nidhitatosaniya we set the value for datepicker through setDate itself. If the issue is coming with Divi theme, pls check this PR from pro plugin - https://github.com/TycheSoftwares/order-delivery-date-pro/pull/6179

**Review by rashmimalpande — APPROVED** [review]
