### PR TITLE
ASAP option displaying first

### LINKED ISSUE #538: "As soon as possible" option should appear first in the dropdown list
**Describe the bug**
"As soon as possible" option should appear at the top

**To Reproduce**
1. Create Delivery time 
2. Enable "Show 'As Soon As Possible' option:" setting
3. you will see that the "As soon as possible" option shows last
image

**Expected behavior**
"As soon as possible" option should appear at the top in the first position.

**Isolating the problem (mark completed items with an [x]):**
- [X] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront]
- [X] I can reproduce this bug consistently using the steps above

**Additional context**
https://support.tychesoftwares.com/conversation/1217?folder_id=9

### PR DESCRIPTION
**Pull request by nidhi-tatosaniya**
"As soon as possible" option appearing first in the dropdown list. Fix #538

### CODE REVIEW

**Review by rashmimalpande — APPROVED** [review]

File: includes/class-orddd-lite-process.php [hunk 1]
```diff
@@ -582,8 +582,6 @@ public static function check_for_time_slot_orddd() {
 
 		$auto_populate_time_slot = get_option( 'orddd_auto_populate_first_available_time_slot' );
 
-		asort( $time_slots_to_show_timestamp );
-
```
Comment (rashmimalpande) [inline includes/class-orddd-lite-process.php:586]: Please check if the timeslots are being sorted or not?

**Review by rashmimalpande — APPROVED** [review]
