### PR TITLE
Fix #478

### LINKED ISSUE #478: Locked out date is not released when a date is changed in the admin order edit page
**Describe the bug**
Looks like a date's lockout limit is not reduced when the the date is changed in admin's order edit page

**To Reproduce**
1. Go to 'General settings' , set 'Maximum Order Deliveries per day' to 2
2. Place 2 orders any particular date, say December 1st.
3. try to place a 3rd order and you find that December 1st is locked out as 2 orders have been already placed as lockout limit for the date is reached.
4. Go to admin and find the orders placed on the date 'December 1st' and edit the order delivery date for one of the orders and change the date to any other date.
5. Go to front end and try to placed order on December 1st. The locked out date should be available as one of the orders has been moved out of it. but the date is not available, thus the error.

**Expected behavior**
Locked out date should be available for placing order if the date of one of the orders is changed.

### PR DESCRIPTION
**Pull request by nidhitatosaniya**
Fixed Locked out date is not released when a date is changed in the admin order edit page Fix #478

### CODE REVIEW

File: includes/class-orddd-lite-admin-delivery.php [hunk 1]
```diff
@@ -223,6 +223,7 @@ public static function save_delivery_dates() {
 						( $previous_order_h_date == $_POST['h_deliverydate'] ) ) { // phpcs:ignore
 						$timestamp = Orddd_Lite_Common::orddd_lite_get_timestamp( $delivery_date, $date_format );
 						Orddd_Lite_Common::update_order_meta( $order_id, '_orddd_lite_timestamp', $timestamp, $order );
+						Orddd_Lite_Common::orddd_lite_changed_delivery( $previous_order_h_date, $timestamp );
```
Comment (rashmimalpande) [inline includes/class-orddd-lite-admin-delivery.php:226]: @nidhitatosaniya  Check the function orddd_lite_cancel_delivery() in class-orddd-lite-common.php. You can use that here.

**Review by rashmimalpande — APPROVED** [review]
