### PR TITLE
Enhanced delivery date toggle logic for virtual/featured product scenarios

### LINKED ISSUE #651: “Disable Delivery Date and Time Slot Fields for Virtual Products” Hides Field for All Products
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When the “Disable the Delivery Date and Time Slot Fields for Virtual Products” setting is enabled, the delivery date field is getting hidden for all products, not just virtual products.

### Steps to reproduce

1. Enable the setting:
Order Delivery Date Lite → Additional Settings → Disable Delivery Date and Time Slot Fields for Virtual Products.
2. Add a virtual product to the cart → delivery date field is hidden.
3. Add a normal (physical) product to the cart → delivery date field is still hidden.
4. Add both virtual + normal products in the same cart → delivery date field remains hidden.

### Expected behavior

The delivery date field should be hidden only for virtual products.

### WordPress Environment

.

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only our plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### Additional field

https://support.tychesoftwares.com/conversation/14301?folder_id=63

### PR DESCRIPTION
**Pull request by nidhitatosaniya**
Adjusted delivery enable/disable logic to properly handle virtual and featured product combinations. Delivery is disabled when both options are active and the cart contains: all virtual items, all featured items, or a virtual + featured pair. Retains existing behavior for single-option cases.

Fix #651

### CODE REVIEW

File: includes/class-orddd-lite-common.php [hunk 1]
```diff
@@ -523,55 +523,85 @@ public static function orddd_lite_cancel_delivery( $order_id ) {
...
+	            }
+	        }
+
+	        if ( $fields_for_virtual_product === 'on' && $fields_for_featured_product === 'on' ) {
+
+	            if ( $all_virtual ) {
+	                $delivery_enabled = 'no';
+	            } elseif ( $all_featured ) {
+	                $delivery_enabled = 'no';
+	            } elseif ( $product_count == 2 && $has_virtual && $has_featured ) {
```
Comment (rashmimalpande) [inline includes/class-orddd-lite-common.php]: @nidhitatosaniya What happens when there are more than 2 products and one of them is a normal product? Can we make this same as in the pro version?

**Review by rashmimalpande — APPROVED** [review]
