### PR TITLE
Fix #418

### LINKED ISSUE #418: Deprecated is_ajax error shows up when our plugin is active
**Describe the bug**
Some of our users are getting Deprecated `is_ajax` error, use `wp_doing_ajax()` when our plugin is active. Looking through the error, it appears the issue is coming from the _class-orddd-lite-process.php_ file on line 625 and this is fixed when the `is_ajax` is replaced.

More context: [https://wordpress.org/support/topic/deprecated-is_ajax-error-solution/#post-15270993](https://wordpress.org/support/topic/deprecated-is_ajax-error-solution/#post-15270993)

### PR DESCRIPTION
**Pull request by PradeepTyche**
[do-not-scan]

### CODE REVIEW

File: includes/class-orddd-lite-process.php [hunk 1]
```diff
@@ -624,8 +624,8 @@ public static function orddd_lite_add_delivery_date_fee( $cart ) {
 
 		$delivery_on_cart = get_option( 'orddd_delivery_date_on_cart_page' );
 		$is_cart          = is_cart();
-		$is_ajax          = is_ajax();
-
+		$is_ajax          = wp_doing_ajax();
```
Comment (rashmimalpande) [inline includes/class-orddd-lite-process.php:627]: this should work for older versions of WC. Add a condition to check the WC version

**Review by rashmimalpande — CHANGES_REQUESTED** [review]

**Review by rashmimalpande — APPROVED** [review]
